---
- name: Downloading tomcat server
  hosts: myservers
  become: True
  tasks:
    - name: tomcat apache download
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.71/bin/apache-tomcat-9.0.71.tar.gz
        dest: /opt/

    - name: untar tomcate
      shell: tar -xvzf apache-tomcat-9.0.71.tar.gz
      args:
        chdir: /opt/

    - name: removing extra tar files
      shell: rm -rf apache-tomcat-9.0.71.tar.gz
      args:
        chdir: /opt/

    - name: changing name
      shell: mv /opt/apache-tomcat-9.0.71 /opt/tomcat
      args:
        chdir: /opt/

    - name: removing files
      shell: rm -rf /opt/tomcat/webapps/*
      args:
        chdir: /opt/

    - name: starting tomcat
      shell: ./startup.sh
      args:
        chdir: /opt/tomcat/bin/
